dev:
  base_url: "https://example.com"
  api_base_url: "https://jsonplaceholder.typicode.com"
qa:
  base_url: "https://google.com"
  api_base_url: "https://jsonplaceholder.typicode.com"
stage:
  base_url: "https://example.com"
  api_base_url: "https://jsonplaceholder.typicode.com"
prod:
  base_url: "https://example.com"
  api_base_url: "https://jsonplaceholder.typicode.com"
